### PR TITLE
[FIX] Workaround for missing TreeExplainer SHAP dimensions

### PR DESCRIPTION
**Pull request by PrimozGodec**
##### Issues
-  TreeExplainer for XGBClassifier and GradientBoostingClassifier in case of binary classification outputs only explanation for class 1 (skipping class 0). The fix is already a PR in the SHAP library, but it does not look like it will be accepted soon (https://github.com/slundberg/shap/pull/1046).
- explain (for tree explainer) module wrongly imputes SHAP values for classes missing in the training phase. Missing explanations are always appended to the end of the list, which is wrong for cases when the missing type is not the last one.

##### Changes
- Making a workaround for missing explanation for XGBClassifier and GradientBoostingClassifier. 
- fixing imputation 
- increasing the SHAP version
- small PyQt6 compatibility fix (transforming RGB to integers)

### CODE REVIEW

**Comment by PrimozGodec** [comment]
@VesnaT Python 3.11 test failed since the SHAP library is not ready for Python 3.11. As I saw, there is already PR which needs to be considered.

**Review by VesnaT — APPROVED** [review]

**Pull request merged**
